return {
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true
    },
    enabled=true
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2
    },
    enabled=true
  },
  ["workshop-758532836"]={ -- Global Pause
    configuration_options={
      AUTOPAUSECONSOLE=false,
      AUTOPAUSEMAP=false,
      AUTOPAUSESINGLEPLAYERONLY=false,
      ENABLECLIENTPAUSE=true,
      ENABLEHOTKEY=false,
      KEYBOARDTOGGLEKEY="P"
    },
    enabled=true
  },
  ["workshop-837819197"]={ -- FinderMod
    configuration_options={
      active=true,
      gamepadFriendly=true
    },
    enabled=true
  }
}
